### PR TITLE
Updating build.gradle.kts files (now using public artifact servers)

### PR DESCRIPTION
**Pull request by politeRaccoon**

### CODE REVIEW

**Review by davidkun — APPROVED** [review]
so you're free of all internal reps? also, are you going to set up GH actions for CI?

**Comment by politeRaccoon** [comment]
> so you're free of all internal reps? also, are you going to set up GH actions for CI?

Yes -- GH action will be a good next step.  For now, whatever you clone from the repo should be buildable by a random external person

**Comment by yossarian1988** [comment]
Are you gonna publish to Maven central too!?!?

**Comment by politeRaccoon** [comment]
Yes -- GH Action into Maven Central is the goal.   But I won't be doing that tonight or tomorrow.  Hopefully Friday or sometime next week

**Pull request merged**
