### PR TITLE
Rhumb lines

### PR DESCRIPTION
**Pull request by dbaker-mitre**
This adds a Rhumb class that does rhumb line math.

### CODE REVIEW

**Comment by politeRaccoon** [comment]
Here are the following changes I would require/suggest:

1. Must change rhumbDiststance somehow.  The method name implies it returns a "Distance" object.  It does not.  We don't want that confusion.  We either need a method rename or we need to convert he "distance in radians" to a Distance object using  ... ???a conversion that reflects the radius of the earth???.
2. In class docs, add a link to:  https://en.wikipedia.org/wiki/Rhumb_line
3. In class docs, copy/paste the into to the wiki article just to explain what a Rhumb Line is.  I had literally never heard of it until recently
4. Run spotless apply (it will fix the broken build)

Genuine Question:  Is there exactly 1 Rhumb line that joins any two LatLong?  Couldn't you construct multiple Rhumb Lines that pass through the same two LatLongs.  Those lines could have wildly different slopes.  How does `rhumbDiststance` know what "slant angle" to walk from point to point?

**Comment by yossarian1988** [comment]
Jon, you've never heard of Rhumb lines? Haven't you ever read Pedro Nunes' 1537 work on Rhumb lines in _Treatise in Defense of the Marine Chart_?

**Comment by politeRaccoon** [comment]
> Jon, you've never heard of Rhumb lines? Haven't you ever read Pedro Nunes' 1537 work on Rhumb lines in _Treatise in Defense of the Marine Chart_?

I was getting confused between Rhumb lines and those rhoomba vacuum

**Comment by yossarian1988** [comment]
Common mistake. That's from his 1539 work _Treatise in Defense of vacuums_.

**Comment by dbaker-mitre** [comment]
> Common mistake. That's from his 1539 work _Treatise in Defense of vacuums_.

Man I miss this sense of humor.

**Comment by dbaker-mitre** [comment]
> Genuine Question: Is there exactly 1 Rhumb line that joins any two LatLong? Couldn't you construct multiple Rhumb Lines that pass through the same two LatLongs. Those lines could have wildly different slopes. How does `rhumbDiststance` know what "slant angle" to walk from point to point?

No the constant angle constraint makes there only one line from A to B. But there is another line from B to A that goes around the other side of the world.

Rhumb distance assumes a constant angle (by definition) from A to B.

So because the earth is flat in real life you get a perfect straight line on a map and definitely now a spiral on the globe if the earth was in fact actually round

**Comment by politeRaccoon** [comment]
We are good

**Review by politeRaccoon — APPROVED** [review]

**Pull request merged**
